# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.vm.box = "debian/bullseye64"
  config.vm.network "private_network", ip: "192.168.57.10"
  config.vm.provision "shell", path: "bootstrap.sh"
end
